language: node_js
node_js:
  - '6'
before_install:
  - 'npm install -g npm@latest'
services:
  - mongodb
before_script:
  - sleep 15
after_success:
  if ([ "$TRAVIS_BRANCH" == "master" ] || [ ! -z "$TRAVIS_TAG" ]) &&
      [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
    - 'npm run clean && npm run build:client && npm run build:server'
  else
    echo "No Deploy on PR!"
  fi
branches:
  only:
    - master
